name: Benchmark

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      warmup_count:
        description: Perform NUM warmup runs sequentially before the actual benchmark.
        type: string
        required: true

      runs_count:
        description: Perform exactly NUM runs for each command.
        type: string
        required: true

jobs:
  regress:
    name: Benchmark
    concurrency:
      group: ${{ github.workflow }}-benchmark-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Compile sources
        run: npm run compile
      - name: Benchmark
        run: npm run bench
        env:
          WARMUP_COUNT: ${{ inputs.warmup_count }}
          RUNS_COUNT: ${{ inputs.runs_count }}
